from fluent/fluentd

RUN gem install fluent-plugin-elasticsearch --no-rdoc --no-ri --version 4.0.7
#COPY ./fluentd/config/fluent.conf /fluentd/etc/fluent.conf
COPY ./config/fluent.conf /fluentd/etc/fluent.conf


