version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
    - "9200:9200"
    volumes:
    - "./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options"
    

